### ISSUE TITLE
Normal stylus imports do not work

### ISSUE THREAD

**Issue by dcneiner** [anviljs/anvil.js#26]
To reproduce, have two `styl` files in the same directory.

sample1.styl

``` css
body { background: blue }
```

sample2.styl

``` css
@import "sample1"
```

When anvil goes to build, it will throw this error:

`````` plain
/Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:1077
      ext = file.ext();
                 ^
TypeError: Object #<Object> has no method 'ext'
    at StylePipeline.<anonymous> (/Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:1077:18)
    at /Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:493:21
    at /Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:1065:16
    at /Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:487:16
    at Object.oncomplete (/Users/.../.nvm/v0.6.6/lib/node_modules/anvil.js/lib/anvil.js:737:16)
```plain
``````

**Comment by arobson** [comment]
Hey @dcneiner, I'm going to close this one given it's nearly a year old... feel free to re-open if Anvil's still having this issue, my guess is that it got resolved with the great big re-write(s) :clap:
