### ISSUE TITLE
Error: Cannot find module 'Commander'

### ISSUE THREAD

**Issue by tutukin** [anviljs/anvil.js#39]
anvil --lib MyProject fails:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'Commander'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/anvil.js/lib/anvil.js:56:13)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

Solution: 

--- lib/anvil.js        2012-06-11 10:51:29.000000000 +0400
+++ /usr/local/lib/node_modules/anvil.js/lib/anvil.js   2012-06-11 10:48:00.000000000 +0400
@@ -53,7 +53,7 @@
 exports.log = log;
 _ = require("underscore");
 path = require("path");
-Commander = require("Commander").Command;
+Commander = require("commander").Command;
 config = {};
 siteConfig = {
   "source": "src",
@@ -1874,4 +1874,4 @@
   var cli;
   cli = new Cli();
   return cli.run();
-};
+};

**Comment by arobson** [comment]
Hi tutukin,

Thanks for catching that and the fix. If you install the 0.7.9 version of Anvil via NPM, it should address the problem.
