### ISSUE TITLE
Anvil breaks on Windows 7

### ISSUE THREAD

**Issue by szkrd** [anviljs/anvil.js#51]
Using _node v0.8.18_ (with the previous 0.8.8 version anvil always died with a missing dependency error) at the end of the package installation process (_npm install anvil -g_):

```
> anvil.js@0.9.0 postinstall C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js
> node ./init.js

Unhandled exception: TypeError: Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at Anvil.initEnvironment (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:89:69)
    at new Anvil (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:81:8)
    at anvilFactory (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:156:9)
    at Object.<anonymous> (C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js\init.js:17:40)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
anvil.js@0.9.0 C:\Users\szkurdi\AppData\Roaming\npm\node_modules\anvil.js
```

After that `anvil -v` works, but pretty much nothing else (even --help spits out tons of red messages).

Did I miss something? Do I have to install some deps manually? Thank you!

**Comment by rauhryan** [comment]
Same problem on Windows 8

**Comment by jcreamer898** [comment]
The code breaking here is...

``` js
this.env.userName = gitConfig.match(/[\t]name[ ][=][ ](.+)[\n]/ )[1];
this.env.email = gitConfig.match(/[\t]email[ ][=][ ](.+)[\n]/ )[1];
```

Looks like it just needs to do a bit of checking.

**Comment by arobson** [comment]
Thanks for catching this one guys, pretty awful assumption I built into the code there. The issue isn't actually windows related but caused if you have a ~/.gitconfig that doesn't include your username and email (which anvil is using to populate headers or scaffolds that reference those values).

**Comment by szkrd** [comment]
Thanks, it's working now!
