### ISSUE TITLE
Ci mode unstable on Windows

### ISSUE THREAD

**Issue by szkrd** [anviljs/anvil.js#59]
Usually after half an hour the ci instanciated anvil dies with an error message:

```
build completed
        file change in 'c:\szabi\dev\www\sandbox\anvil\scriptloader\src\js\fetch.js'
        prepping '\js\fetch.js'
Unhandled exception: Error: watch ENOENT
Error: watch ENOENT
    at errnoException (fs.js:806:11)
    at FSWatcher.start (fs.js:837:11)
    at Object.fs.watch (fs.js:861:11)
    at Object.module.exports.watch (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\fs-watch-tree\lib\fs-watcher.js:40:25)
    at watchFile (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\fs-watch-tree\lib\tree-watcher.js:97:17)
    at EventEmitter.watch (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\fs-watch-tree\lib\tree-watcher.js:105:20)
    at EventEmitter.emit (events.js:126:20)
    at Array.forEach (native)
    at EventEmitter.<anonymous> (C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\fs-watch-tree\lib\change-tracker.js:53:17)
    at C:\Users\szabi\AppData\Roaming\npm\node_modules\anvil.js\node_modules\fs-watch-tree\lib\async.js:15:21
```

I know it's terribly vague and I couldn't easily reproduce the problem but basically this is the number one reason for me restarting a ci anvil. After this message anvil won't exit, but it won't build either. If this can't be fixed or should be reported upstream (_fs-watch-tree_), please let me know and just close the bug. Thanks!

**Comment by arobson** [comment]
@rosamez - thank you for reporting this one. I suggest reporting it to fs-watch-tree. I can say that on Linux, I haven't seen the same behavior yet. Keep me posted, file watching seems to be very unpredictable in general.

**Comment by szkrd** [comment]
I think I'm going to give up file watching :( It's totally useless / unreliable on Windows (and I find it annoying how node itself sidesteps the problem by stating that fs.watch is not cross platform); eventually the time between crashes are down to mere minutes rendering my workflow more of a pain than a workflow.

I will close this one since the bug is not clearly reproducable and it happens with every fs-watch style node project on windows. I probably will bridge-network one of my linux vms and share the dev folder; reporting upstream: maybe.
