### ISSUE TITLE
Windows 7: Anvil uglify throws error on example project.

### ISSUE THREAD

**Issue by magicwrites** [anviljs/anvil.js#65]
Hey,

I've followed the instructions from anviljs website and installed node (v 0.10.3), npm (v 1.2.17) and anviljs (v 0.9.4). When I tried to set up a simple project with concatenation and minification, I get an ugly error on "post-processing".

I downloaded an example project that Wiki pointed me to (postal in this case) and it broke too. Seems like this is a problem with anvil uglify, but I posted it here since all I've done was to follow the website tutorials.

``` cmd
starting activity, post-process
        plugin: 'anvil.uglify'
Uglifying 1 files
 error running activity post-process : TypeError: Arguments to path.join must be
 strings
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at anvil.plugin.minify (C:\Users\Maur\.anvilextensions\node_modules\anvil.ug
lify\lib\uglify.js:194:100)
    at C:\Users\Maur\AppData\Roaming\npm\node_modules\anvil.js\lib\scheduler.js:
35:4
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Maur\AppData\Roaming\npm\node_modules
\anvil.js\node_modules\underscore\underscore.js:78:11)
    at Scheduler.parallel (C:\Users\Maur\AppData\Roaming\npm\node_modules\anvil.
js\lib\scheduler.js:34:5)
    at anvil.plugin.run (C:\Users\Maur\.anvilextensions\node_modules\anvil.uglif
y\lib\uglify.js:163:33)
    at C:\Users\Maur\AppData\Roaming\npm\node_modules\anvil.js\lib\activityManag
er.js:104:21
```

Any clues on what's wrong?

**Comment by dcneiner** [comment]
Hey @maciejmazur – sorry for the trouble you are experiencing. There is currently an open issue in the uglify repo: https://github.com/arobson/anvil.uglify/pull/4 That is just waiting on a merge… once that is pulled in you should be all set.

If you wanted to try to pull that version in sooner, you can install Tyson's fixed version locally to your project.
1. In your directory, run `npm install git://github.com/tysoncadenhead/anvil.uglify.git`
2. So that Anvil knows to use your local version, in your build.json, add the following:

``` json
{
    ... existing configuration ...

    "extensions": {
       "local": [ "anvil.uglify" ]
    }
}
```

cc: @arobson @tysoncadenhead
